### ISSUE TITLE
Can't open Spykeviewer

### ISSUE THREAD

**Issue by Helveg** [rproepp/spykeviewer#15]
Hello there, I'm trying out SpykeViewer, and I haven't been succesful opening the GUI. Few things that happened:

* The download link http://www.ni.tu-berlin.de/software/spykeviewer on https://spyke-viewer.readthedocs.io/en/latest/installation.html, takes the user to the download page for `neurolib`.
* After finding the right page, neither the MacOS nor Windows binary download links actually start a download (Chrome browser)
* After `pip install spykeviewer`, running `spykeviewer` briefly turns my cursor into a loading spinner, but then nothing happens. (Windows)

**Comment by rproepp** [comment]
It seems that the institute links don't work for the download, but the links are still good (e.g. copying into a browser address bar should download the file even though clicking the link may not work): http://spyke-viewer.g-node.org/static/spykeviewer-windows-0.4.1.zip http://spyke-viewer.g-node.org/static/spykeviewer-0.4.1.dmg

Since Spyke Viewer hasn't been in active development for a while,´you may run into version conflicts when trying to run it from source.

**Comment by Helveg** [comment]
Oh, are there any actively maintained forks, or similar projects for visualization of data using neo?

**Comment by rproepp** [comment]
I don't work in the field anymore so I'm not aware of the latest developments, but https://github.com/NeuralEnsemble/ephyviewer seems like a mroe recent alternative.
